# Generated by Django 2.2.4 on 2024-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='problempost',
            name='solution',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
