# Generated by Django 2.2.4 on 2024-05-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
    ]
