# Generated by Django 2.2.4 on 2024-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_remove_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
