# Generated by Django 2.2.4 on 2024-05-23 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oj.models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_submission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problempost',
            options={'ordering': ('created',)},
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, upload_to=oj.models.input_file_upload_to)),
                ('output_file', models.FileField(blank=True, upload_to=oj.models.output_file_upload_to)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.ProblemPost')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
