# Generated by Django 2.2.4 on 2024-05-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='descripton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
