# Generated by Django 2.2.4 on 2024-05-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20240517_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
