# Generated by Django 2.2.4 on 2024-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20240517_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='video/%Y%m%d/'),
        ),
    ]
