# Generated by Django 2.2.4 on 2024-05-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlepost_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='video/%Y%m%d/'),
        ),
    ]
